name: flutter_bloc_pagination
description: A simple and flexible pagination controller for Flutter BLoC, allowing page-by-page data loading, refresh, and easy integration with BlocBuilder.
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

homepage: https://github.com/amirsalarrabaniha/bloc_pagination
repository: https://github.com/amirsalarrabaniha/bloc_pagination